# Generated by Django 3.2.13 on 2022-10-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
